#!/bin/bash

## This scritp is meant for debian like distro, basically distro which uses apt as their package manager.

dirx= pwd ; ~/.config/polybar/requirments ; git clone https://github.com/polybar/polybar.git ~/.config/polybar/polybar_git ; ~/.config/polybar/polybar_git/build.sh ; echo " Polybar is installed and upto date. ; $(polybar -v) " ; rm -rf ~/.config/polybar/polybar_git ;

echo "Just go to ~/.config/polybar/ and rename either config_mine or config_default for the configuration file. And now run polybar to start polybar.
